In [108]:
# this notebook strips all white space, including metadata at bottom of image leaving only the map image

In [109]:
import numpy as np
from PIL import Image

In [110]:
folder = 'origin'
fname = '002_007'

In [111]:
pic = Image.open(folder + '\\' + fname + '.jpg')

In [112]:
image = np.array(pic)

In [113]:
# create boolean mask, white is True
white = np.array([255, 255, 255])
mask = np.abs(image - white).sum(axis=2) < 0.05

In [114]:
white

array([255, 255, 255])

In [115]:
coords = np.array(np.nonzero(~mask))
top_left = np.min(coords, axis=1)
bottom_right = np.max(coords, axis=1)

out = image[top_left[0]:bottom_right[0],
            top_left[1]:bottom_right[1]]

In [116]:
# Image.fromarray(out)

In [117]:
# white is True
# mask = np.abs(out - white).sum(axis=2) < 0.05
mask_white = out == [255, 255, 255]
mask_black = out == [0, 0, 0]
mask = mask_white + mask_black

white_arr = np.all(mask, axis = 2)
white_arr = ~white_arr

In [118]:
white_rows  = white_arr.any(axis=1)
# white_rows

In [119]:
np.unique(white_rows)

array([False,  True])

In [120]:
white_index = np.where(white_rows == False)
lower_bound = min(white_index[0])

In [121]:
white_index

(array([1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863], dtype=int64),)

In [122]:
trim = 10

In [123]:
out2 = out[trim:lower_bound-trim, trim:-trim]

In [124]:
output = Image.fromarray(out2)

In [125]:
output.save( folder + '\\stripped_' + fname + '.jpg' )